language: python
python:
    - 3.4
    - 3.5

install:
    - pip install -r requirements/base.txt

script:
        # пока не ясно, что это делает
    - pylint planner/planner
        # чекает все файлы с расширением .py
    - find . -iname "*.py" |xargs pylint --rcfile .pylintrc

sudo: false

matrix:
    fast_finish: true
