language: python
python:
    - 3.4
    - 3.5

install:
    - pip install -r requirements/base.txt

script:    
        # пока не ясно, что это делает 
    - pylint TopProject/todo   
        # чекает все файлы с расширением .py                   
    - find . -iname "*.py" |xargs pylint   

sudo: false

matrix:
    fast_finish: true
