# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/None/no-img.png', upload_to='users/images/'),
        ),
    ]
