# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20170420_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('in_progress', 'Выполняется'), ('ready', 'Выполнена')], max_length=11),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
