# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20170520_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='src/static/users/images/no-img.png', upload_to='src/static/users/images/'),
        ),
    ]
