# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20170520_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/images/no-img.png', upload_to='users/images/'),
        ),
    ]
