# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20170424_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
