# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20170520_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statistics',
            field=models.ImageField(blank=True, upload_to='users/statistics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=src.models.UploadTo('users/images/')),
        ),
    ]
