# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20170424_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', related_query_name='scores', to='src.Task'),
        ),
    ]
