# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20170425_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', related_query_name='score', to='src.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('in_progress', 'Выполняется'), ('ready', 'Выполнена')], default='in_progress', max_length=11),
        ),
    ]
